FROM python:3.11-slim
WORKDIR /app
COPY ../dashboards/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ../dashboards /app
CMD ["streamlit", "run", "home.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
